### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by Lansieuva** [chehx/DGDR#3]
Thank you for your work, it's impressive! However, I ran into some problems reproducing the experiment, and the links of the dataset you provided are no longer working. For example IDRID, RLDR and EyePACS are not available, can you please update or share them to me as google drive or Baidudisk. My email is rsjingjuny@whu.edu.cn. Thanks again!

**Comment by chehx** [comment]
Thanks for your interest in our work!
Have you tried the provided one drive link?

`Due to the license issue, you can download the processed datasets we provided here (GDRBench [images](https://hkustconnect-my.sharepoint.com/:u:/g/personal/hche_connect_ust_hk/ETmoy8HPK5RCl0X075HYiF0ByLAkUcBGnoM75BcP8CefjA?e=KcqN0h) and [masks](https://hkustconnect-my.sharepoint.com/:f:/g/personal/ychengbj_connect_ust_hk/EsRUyE6bkrlKhSZdND4OygABKV6mHZzjfMj-cJA1zUVXPg?e=VbtD6q)), except FAGDR and MESSIDOR-2.`

**Comment by Lansieuva** [comment]
Thank you very much for your prompt reply! So after downloading the data you processed in the link, do I still need to download and preprocess the FAGDR and MESSIDOR-2 data according to the guideline? Thanks!

**Comment by chehx** [comment]
Yes. Since they have restricted sharing rules, we cannot distribute them online.

**Comment by Lansieuva** [comment]
Sincerely, thank you!
